#!/usr/bin/env python
'''
This is a helpful wrapper to run CKAN paster commands, so instead of running:

    paster --plugin=ckan sysadmin add admin -c /etc/ckan/default/production.ini

you can run

    ckan sysadmin add admin


'''
import os
import sys
from pkg_resources import load_entry_point


paster_commands = ['create', 'help','make-config',
                   'points','post','request',
                   'serve','setup-app']
config = False


for num, arg in enumerate(sys.argv):
    if arg[:2] == '-i':
        instance = sys.argv[num + 1]
        sys.argv.pop(num)
        sys.argv.pop(num)
    if arg[:2] == '-c' or arg.startswith('--config'):
        config = True

if not config:
    try:
        config_file = '/srv/app/production.ini'
        fh = open(config_file)
    except IOError as e:
        raise Exception('No production.ini in /srv/app. '
                        'Create one or use the -c config_file option')

if not config and len(sys.argv) > 1:
    if sys.argv[1] not in paster_commands:
        sys.argv.append('-c')
        sys.argv.append(config_file)
    # paster commands just accept config file as last arg
    if sys.argv[1] in ['serve', 'setup-app']:
        sys.argv.append(config_file)


sys.argv.insert(1, '--plugin=ckan')

if __name__ == '__main__':
    sys.exit(
        load_entry_point('PasteScript', 'console_scripts', 'paster')()
    )
